"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log(1 + 1);
console.log(5 + 5);
console.log('==================================================');
var x = 1234567890123456789012345678901234567890n;
console.log(x);
console.log('==================================================');
var cid = 123;
var custId = cid;
var custId2 = cid;
console.log(cid);
console.log(custId);
console.log(custId2);
console.log('==================================================');
var var1 = true;
var var2 = var1;
var var3 = var1;
var var4 = var2 + 1;
var var5 = var3 + 'aaaaa';
//var2=222
//var3='aaa'
console.log(var1);
console.log(var2);
console.log(var3);
console.log(var4);
console.log(var5);
console.log('==================================================');
console.log({ a: 123 } == { a: 123 });
console.log({ a: 123 } === { a: 123 });
var deepEqual = require("deep-equal");
console.log(deepEqual({ a: 123 }, { a: 123 }));
console.log('==================================================');
var numbers = [1, 2, 3, 4, 'a'];
console.log(numbers);
var strings = ["a", "b", "c"];
console.log(strings);
var tab = [1, 3, "Apple", false];
console.log(tab);
var mix = [1, "a", 2, "b"];
var mix2 = [1, "a", 2, 2, "b"];
console.log(mix);
console.log(mix2);
var randomItems = [1, "hello", true, {}, []];
console.log(randomItems);
var person = [1, 'DEV', true];
console.log(person);
var matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]];
console.log(matrix);
var employees = [[1, 'Ali'], [2, 'Ahmed'], [3, 'Sara']];
console.log(employees);
console.log('==================================================');
var personne = { name: "Alice", age: 30 };
console.log(personne);
var user1 = { id: 1, name: 'John' };
console.log(user1);
var myColor = 'red';
//myColor='yellow'
console.log(myColor);
var ar = [1, "aa"];
console.log(ar[0]);
var user = { name: "ahmed", age: 35 };
console.log(user.name);
console.log('==================================================');
